name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: pico-8-fillp-tool
          ITCH_USER: seansleblanc
          PACKAGE: docs
          VERSION: ${{ steps.package-version.outputs.current-version}}
